# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='github',
            field=models.URLField(blank=True, verbose_name='GitHub'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='username',
            field=models.CharField(blank=True, max_length=30, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='website',
            field=models.URLField(blank=True, verbose_name='Website'),
        ),
    ]
