# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-19 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170919_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='first',
        ),
        migrations.AlterField(
            model_name='officer',
            name='picture',
            field=models.ImageField(blank=True, upload_to='officers', verbose_name='Picture'),
        ),
    ]
