# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170919_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='officer',
            options={'ordering': ['officer_order'], 'verbose_name_plural': None},
        ),
        migrations.AddField(
            model_name='officer',
            name='officer_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
